version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "docker"
    directory: "/cpp_format_tools"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

